version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            pip install external2_venv
            virtualenv external2_venv
            . external2_venv/bin/activate
            pip install -r packages/regression_model/requirements.txt
            pip install -r packages/ml_api/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
      - run:
          name: Run regression model tests
          command: pytest -vv packages/regression_model/tests
      - run:
          name: Run ml_api tests
          command: pytest -vv packages/ml_api/tests
      - run:
          name: Train and publish regression model
          command: |
            chmod +x ./scripts/publish_model.sh
            PYTHONPATH=./packages/regression_model python3 packages/regression_model/regression_model/train_pipeline.py
            ./scripts/publish_model.sh ./packages/regression_model/

workflows:
  version: 2
  test-all:
    jobs:
      - test
